Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: true
    # GoogleFonts: "Fira+Sans+Condensed:400|Nunito:700&display=swap[async]"
    Packages:
      'Abte.Site':
        Package: 'Abte.Site'
        General:
          Head: 
            - https://use.typekit.net/vgp6vke.css
            - Alicante.css
            # Alicante is 8280dda7-93d2-4564-87ef-68181ac2ff35
            - https://stats.abteilung.tools/tracker.js[async data-ackee-server="https://stats.abteilung.tools" data-ackee-domain-id="8280dda7-93d2-4564-87ef-68181ac2ff35"]
          Body: 
            - Alicante.js[defer]
            - Ackee.js[defer][inline]