Alicante:
  FuseJs:
    alwaysInclude: true
    selector:
      onDocument: '[instanceof Alicante.Forms:Include]'
      collection: '[instanceof Neos.Neos:ContentCollection]'
      content: '[instanceof Alicante.Forms:Include]'