Neos:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'mail.cyon.ch'
        port: '465'
        encryption: 'ssl'
        username: 'contact@alicante.realestate'
        password: 'TqP<q$>6qCW.JJi'
        localDomain: 'mail.cyon.ch'