'Abte.Site:Document.Product':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Product': true
    'Abte.Site:Mixin.Image': true
    'Abte.Site:Mixin.PropertyFeatures': true
    'Alicante.Flickity:Include': true
    'Abte.Site:Mixin.New': true
    'Abte.Site:Mixin.Hero': true
    'Abte.Site:Constraint.Document.Restricted': true
    'Abte.Site:Mixin.Searchable.SiteSearch': true
  label: "${ q(node).property('isHero') && node.context.inBackend ? '<span class=\"hidden\">🏆 </span>' + q(node).property('title') : q(node).property('isNew') && node.context.inBackend ? '<span class=\"hidden\">🆕 </span>' + q(node).property('title') : q(node).property('title') }"
  ui:
    icon: fort-awesome
    label: Property
    position: 700
  constraints:
    nodeTypes:
      '*': false
  properties:
    'image':
      options:
        preset: 'image.headerAsset'
      ui:
        inspector:
          position: 1
    'address':
      options:
        preset: 'text.plain'
      ui:
        inline:
          editorOptions:
            placeholder: Address of Property
    'description':
      options:
        preset: 'text.free'
    'images':
      options:
        preset: 'image.assets'
      ui:
        label: Further Images
        inspector:
          group: 'image'
    'floorPlans':
      options:
        preset: 'image.assets'
      ui:
        label: Floorplans
        inspector:
          group: 'image'
    'categories':
      type: references
      ui:
        label: 'Kategorien'
        reloadIfChanged: TRUE
        inspector:
          group: 'document'
          position: 20
          editorOptions:
            nodeTypes: ['Abte.Site:Document.Category']
            # startingPoint: "ClientEval:node.properties._path.replace(/(.+)(\\/.+)/, '$1')"
    geoCoordinates:
      type: string
      ui:
        label: Geolocation
        inspector:
          label: GeoLocation
          group: document
          position: 95
          editor: "Abte.GeoCoding/GeoCodingEditor"
          editorOptions:
            googleApiKey: ''
            div: ";"
            # zip: "ClientEval:node.properties.company_zip"
            # city: "ClientEval:node.properties.company_city"
            address: "ClientEval:node.properties.address"            